server:
  port: 8082
  error:
    include-message: always
spring:
#  jmx:
#    enabled: true
  webflux:
    base-path: /api
  # Variabili hardcoded per comodità di testing
  r2dbc:
    name: postgres
    username: adri
    password: password
    url: r2dbc:postgresql://172.17.0.2:5432/postgres?schema=analysis

#logging:
#  level:
#    org:
#      springframework:
#        r2dbc: DEBUG

greetings:
  sse-count: 10

google.api:
  user-email: ${SERVICE_USR_EMAIL}
  privateKey: ${PRIVATE_KEY}
  scopes: ${SCOPES}
  storage-api-url: https://storage.googleapis.com
  auth-url: https://oauth2.googleapis.com/token
  grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
  bucket-name: ${BUCKET_NAME}
code:
  days-till-removal: 30
