name: Build quarkus-reactive
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feature/*
    paths:
      - '.github/workflows/build-test-quarkus-reactive.yml'
      - 'quarkus/quarkus-reactive/**'
      - '!quarkus/quarkus-reactive/README.md'
      - '!quarkus/quarkus-reactive/gralde/**'
      - '!quarkus/quarkus-reactive/graldew.bat'
      - '!quarkus/quarkus-reactive/graldew'
jobs:
  build-and-test:
    uses: latusikl/jvm-frameworks-comparative-assessment/.github/workflows/build-test-gradle.yml@develop
    with:
      application-dir: quarkus/quarkus-reactive
