name: Build spring-boot-reactive
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feature/*
    paths:
      - ".github/workflows/build-test-spring-boot-reactive.yml"
      - "spring-boot/spring-boot-reactive/**"
      - "!spring-boot/spring-boot-reactive/README.md"
      - "!spring-boot/spring-boot-reactive/gralde/**"
      - "!spring-boot/spring-boot-reactive/graldew.bat"
      - "!spring-boot/spring-boot-reactive/graldew"
jobs:
  build-and-test:
    uses: latusikl/jvm-frameworks-comparative-assessment/.github/workflows/build-test-gradle.yml@develop
    with:
      application-dir: spring-boot/spring-boot-reactive
