name: Build micronaut-reactive
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - feature/*
    paths:
      - '.github/workflows/build-test-micronaut-reactive.yml'
      - 'micronaut/micronaut-reactive/**'
      - '!micronaut/micronaut-reactive/README.md'
      - '!micronaut/micronaut-reactive/gralde/**'
      - '!micronaut/micronaut-reactive/graldew.bat'
      - '!micronaut/micronaut-reactive/graldew'
jobs:
  build-and-test:
    uses: latusikl/comparative-analysis/.github/workflows/build-test-gradle.yml@develop
    with:
      application-dir: micronaut/micronaut-reactive
