name: Publish spring-boot-reactive
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-spring-boot-reactive.yml'
      - 'spring-boot/spring-boot-reactive/**'
      - '!spring-boot/spring-boot-reactive/README.md'
      - '!spring-boot/spring-boot-reactive/gralde/**'
      - '!spring-boot/spring-boot-reactive/graldew.bat'
      - '!spring-boot/spring-boot-reactive/graldew'
      
jobs:
  build-image-and-publish:
    uses: latusikl/jvm-frameworks-comparative-assessment/.github/workflows/publish-image.yml@main
    with:
      application-dir: spring-boot/spring-boot-reactive
      image-tag: spring-boot-reactive
    secrets:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      USR: ${{ secrets.DOCKER_USR }}
      KEY: ${{ secrets.DOCKER_KEY }}
